# @package _global_

defaults:
  - _self_
  - data: dataset1.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: dataset1.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/train/runs/2023-05-04_08-22-36/checkpoints/epoch_099.ckpt
