# @package _global_

defaults:
  - _self_
  - data: dataset3.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: dataset3.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/train/runs/2023-05-05_11-33-55/checkpoints/epoch_062.ckpt
